### ISSUE TITLE
java.lang.NoSuchMethodError while running Gtfs2TransitSchedule

### ISSUE THREAD

**Issue by china-shuai** [matsim-org/pt2matsim#144]
Hello everyone, 
When I use gtfs2transitschedule to convert Gtfs to matsim schedule, an error prompt for java.lang.nosuchmethoderror will appear.
Error :
> Exception in thread "main" java.lang.NoSuchMethodError: org.matsim.pt.transitSchedule.api.TransitRouteStop.getArrivalOffset()Lorg/matsim/core/utils/misc/OptionalTime;
	at org.matsim.pt2matsim.tools.debug.ScheduleCleaner.combineIdenticalTransitRoutes(ScheduleCleaner.java:318)
	at org.matsim.pt2matsim.gtfs.GtfsConverter.combineTransitRoutes(GtfsConverter.java:297)
	at org.matsim.pt2matsim.gtfs.GtfsConverter.convert(GtfsConverter.java:116)
	at org.matsim.pt2matsim.gtfs.GtfsConverter.convert(GtfsConverter.java:71)
	at org.matsim.pt2matsim.run.Gtfs2TransitSchedule.run(Gtfs2TransitSchedule.java:107)
	at org.matsim.pt2matsim.run.Gtfs2TransitSchedule.main(Gtfs2TransitSchedule.java:69)
	at a_shuai.main(a_shuai.java:12) 

Matsim Versions
matsim: 12.0
pt2matsim: 21.4

My code

> String[] aa = new String[4];
aa[0] = "E:\\eclipse work\\pt2matsim-master\\example\\input\\addisoncounty-vt-us-gtfs";
aa[1] = "all";
 aa[2] = "WGS84";
aa[3] = "E:\\eclipse work\\pt2matsim-master\\example\\input\\addisoncounty-vt-us-gtfs";
 Gtfs2TransitSchedule.main(aa);

Thank you for all help.

**Comment by polettif** [comment]
This looks like an issue with a dependency on MATSim 12, please have a look at #134.

**Comment by china-shuai** [comment]
Thank you for your help. The problem has been solved.
