### ISSUE TITLE
Issue with public transit mapper

### ISSUE THREAD

**Issue by Sasha740** [matsim-org/pt2matsim#191]
Hello,
I'm using pt2matsim to map network.xml with schedule.xml. I'll try to explain myself as clear as possible.

1. I downloaded first the .osm map, and using the MATSim to generate the **_network.xml_**. After that, I downloaded the GTFS files, executed first the GTFS2Transit to generate both **_the transit_** and **_the vehicles_**,
2. Then I want to  map network.xml with schedule.xml. I generated the config file with **_CreateDefaultPtMapperConfig_SZ.xml_**, and run the following code to generate the final transit and network.
            `package Sasha;
            import org.matsim.pt2matsim.run.PublicTransitMapper;
            public class Mapper {
                public static void main(String[] args) {
                    // TODO Auto-generated method stub
                    String[] aa = new String[1];
                    aa[0] = "src/main/java/Sasha/defaultPTMapperConfig_SZ.xml";
                    PublicTransitMapper.main(aa);
                }
            }`

3. When I run the above code , I got the error
`Exception in thread "Thread-0" java.lang.NoSuchMethodError: org.matsim.core.network.filter.NetworkFilterManager.<init>(Lorg/matsim/api/core/v01/network/Network;)V
	at org.matsim.pt2matsim.tools.NetworkTools.createFilteredNetworkByLinkMode(NetworkTools.java:228)
	at org.matsim.pt2matsim.mapping.networkRouter.ScheduleRoutersStandard.load(ScheduleRoutersStandard.java:90)
	at org.matsim.pt2matsim.mapping.networkRouter.ScheduleRoutersStandard.<init>(ScheduleRoutersStandard.java:60)
	at org.matsim.pt2matsim.mapping.networkRouter.ScheduleRoutersStandard.<init>(ScheduleRoutersStandard.java:36)
	at org.matsim.pt2matsim.mapping.networkRouter.ScheduleRoutersStandard$Factory.createInstance(ScheduleRoutersStandard.java:184)
	at org.matsim.pt2matsim.mapping.PseudoRoutingImpl.run(PseudoRoutingImpl.java:77)
	at java.base/java.lang.Thread.run(Thread.java:834)`

I'll attach the zip of the log file , maybe I messed up in the generation of the config file.

Kind regards,
Sasha Song
[log.log](https://github.com/matsim-org/pt2matsim/files/12023632/log.log)

**Comment by polettif** [comment]
Hard to tell what's going on without the config file. Two things stood out to me:
- `search radius: 30000.0` is too big for link candidates (assuming it's in meters)
- `java.lang.NoSuchMethodError: org.matsim.core.network.filter.NetworkFilterManager.<init>(Lorg/matsim/api/core/v01/network/Network` looks to me like some issue with the matsim dependency, it should be matsim 15.0 (as stated pom.xml)
