### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "org.matsim.api.core.v01.network.Link.getId()" because "linkTo" is null

### ISSUE THREAD

**Issue by GioC99** [matsim-org/pt2matsim#193]
hello, when running the project I have this error during the plausibility check. has anyone ever seen this or know how to solve it, it seems to appear only with certain parameters.
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "org.matsim.api.core.v01.network.Link.getId()" because "linkTo" is null
	at org.matsim.pt2matsim.plausibility.PlausibilityCheck.runCheck(PlausibilityCheck.java:156)
	at org.matsim.pt2matsim.run.CheckMappedSchedulePlausibility.run(CheckMappedSchedulePlausibility.java:96)
	at org.matsim.pt2matsim.examples.PT2MATSimExample.checkPlausibility(PT2MATSimExample.java:207)
	at org.matsim.pt2matsim.examples.PT2MATSimExample.main(PT2MATSimExample.java:76)

**Comment by GioC99** [comment]
It seems that the problem happens when I put the number of link thresholds over 6 in the PublicTransitMappingConfigGroup

**Comment by polettif** [comment]
The issue is hard to reproduce without an example of the schedule and network. In theory the number of link candidates used should have no influence on whether a schedule is valid or not. If the schedule is valid (i.e. no toLinks missing), then the plausibility check should run without issues.

**Comment by GioC99** [comment]
i think the problem was that i was using an open street map that didn't cover a big enough part of the network of the transit schedule, so that may have created the issue

**Comment by polettif** [comment]
Alright, thanks for the update 👍
