### ISSUE TITLE
Latest CH HAFAS

### ISSUE THREAD

**Issue by sebhoerl** [matsim-org/pt2matsim#21]
There is problem with loading the latest HAFAS schedule for Switzerland:
https://opentransportdata.swiss/de/dataset/timetable-2017-hrdf/resource/c8d6b488-3551-4fae-9774-1ef378d67980

    2017-09-28 15:15:28,813  INFO Counter:61 FPLAN line # 1
    
    Exception in thread "main" java.lang.NumberFormatException: For input string: "  "
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:569)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.matsim.pt2matsim.hafas.lib.FPLANReader.parseFPLAN(FPLANReader.java:108)
	at org.matsim.pt2matsim.hafas.HafasConverter.run(HafasConverter.java:74)
	at org.matsim.pt2matsim.run.Hafas2TransitSchedule.run(Hafas2TransitSchedule.java:74)
	at org.matsim.pt2matsim.run.Hafas2TransitSchedule.main(Hafas2TransitSchedule.java:58)

This (optional) time information that the code refers to doesn't seem to be there anymore?

**Comment by sebhoerl** [comment]
Beginning of the schedule:

    
    *Z 03002 06____   001                                     % -- 4940034757 -- 
    *G RB  8050807 8091916                                    %
    *A VE 8050807 8091916 006882                              %
    *A TS 8050807 8091916                                     %
    *R                                                        %
    8050807 Hüffenhardt                  01142                %
    8050806 Siegelsbach           01146  01146                %
    8050805 Obergimpern           01152  01152                %
    8050804 Untergimpern          01156  01156                %
    8050803 Neckarbischofsheim H  01159  01159                %
    8050802 Neckarbischofsheim S  01205  01205                %
    8091916 Neckarbischofsheim N  01212                       %
