### ISSUE TITLE
Problem with creating TransitSchedule

### ISSUE THREAD

**Issue by steven224** [matsim-org/pt2matsim#30]
Hi, I am  ok with create multimode network, but not able to get schedule file..please help 

D:\sfsong\Desktop\Simulation>java -cp pt2matsim-18.1.1-shaded.jar org.matsim.pt2matsim.run.Osm2TransitSchedule map.osm schedule.xml
2018-02-09 14:29:42,902  INFO Config:131 context=[file:/D:/sfsong/Desktop/Simulation/]
2018-02-09 14:29:42,983  INFO Config:131 context=[file:/D:/sfsong/Desktop/Simulation/]
2018-02-09 14:29:43,013  INFO MatsimXmlParser:147 starting to parse xml from file map.osm ...
2018-02-09 14:29:43,020  INFO Counter:61 node 1
2018-02-09 14:29:43,021  INFO Counter:61 node 2
2018-02-09 14:29:43,021  INFO Counter:61 node 4
2018-02-09 14:29:43,022  INFO Counter:61 node 8
2018-02-09 14:29:43,023  INFO Counter:61 node 16
2018-02-09 14:29:43,025  INFO Counter:61 node 32
2018-02-09 14:29:43,029  INFO Counter:61 node 64
2018-02-09 14:29:43,034  INFO Counter:61 node 128
2018-02-09 14:29:43,047  INFO Counter:61 node 256
2018-02-09 14:29:43,066  INFO Counter:61 node 512
2018-02-09 14:29:43,087  INFO Counter:61 node 1024
2018-02-09 14:29:43,111  INFO Counter:61 node 2048
2018-02-09 14:29:43,137  INFO Counter:61 node 4096
2018-02-09 14:29:43,190  INFO Counter:61 node 8192
2018-02-09 14:29:43,250  INFO Counter:61 node 16384
2018-02-09 14:29:43,380  INFO Counter:61 node 32768
2018-02-09 14:29:43,395  INFO Counter:61 way 1
2018-02-09 14:29:43,398  INFO Counter:61 way 2
2018-02-09 14:29:43,401  INFO Counter:61 way 4
2018-02-09 14:29:43,403  INFO Counter:61 way 8
2018-02-09 14:29:43,406  INFO Counter:61 way 16
2018-02-09 14:29:43,407  INFO Counter:61 way 32
2018-02-09 14:29:43,417  INFO Counter:61 way 64
2018-02-09 14:29:43,421  INFO Counter:61 way 128
2018-02-09 14:29:43,432  INFO Counter:61 way 256
2018-02-09 14:29:43,448  INFO Counter:61 way 512
2018-02-09 14:29:43,463  INFO Counter:61 way 1024
2018-02-09 14:29:43,492  INFO Counter:61 way 2048
2018-02-09 14:29:43,520  INFO Counter:61 relation 1
2018-02-09 14:29:43,523  INFO Counter:61 relation 2
2018-02-09 14:29:43,528  INFO Counter:61 relation 4
2018-02-09 14:29:43,537  INFO Counter:61 relation 8
2018-02-09 14:29:43,545  INFO Counter:61 relation 16
2018-02-09 14:29:43,547  INFO Counter:61 relation 32
2018-02-09 14:29:43,557  INFO Counter:61 relation 64
2018-02-09 14:29:43,566  INFO OsmDataImpl:51 Build map...
2018-02-09 14:29:43,567  INFO OsmDataImpl:56 Create ways...
2018-02-09 14:29:43,567  INFO Counter:61  # 1
2018-02-09 14:29:43,573  INFO Counter:61  # 2
2018-02-09 14:29:43,574  INFO Counter:61  # 4
2018-02-09 14:29:43,579  INFO Counter:61  # 8
2018-02-09 14:29:43,580  INFO Counter:61  # 16
2018-02-09 14:29:43,581  INFO Counter:61  # 32
2018-02-09 14:29:43,583  INFO Counter:61  # 64
2018-02-09 14:29:43,585  INFO Counter:61  # 128
2018-02-09 14:29:43,589  INFO Counter:61  # 256
2018-02-09 14:29:43,598  INFO Counter:61  # 512
2018-02-09 14:29:43,607  INFO Counter:61  # 1024
2018-02-09 14:29:43,647  INFO Counter:61  # 2048
2018-02-09 14:29:43,666  INFO OsmDataImpl:88 Create relations...
2018-02-09 14:29:43,667  INFO Counter:61  # 1
2018-02-09 14:29:43,669  INFO Counter:61  # 2
2018-02-09 14:29:43,670  INFO Counter:61  # 4
2018-02-09 14:29:43,671  INFO Counter:61  # 8
2018-02-09 14:29:43,675  INFO Counter:61  # 16
2018-02-09 14:29:43,676  INFO Counter:61  # 32
2018-02-09 14:29:43,676  INFO Counter:61  # 64
2018-02-09 14:29:43,703  INFO Counter:67 node 34326
2018-02-09 14:29:43,703  INFO Counter:67 way 3112
2018-02-09 14:29:43,705  INFO Counter:67 relation 92
Exception in thread "main" java.lang.NullPointerException
        at org.matsim.pt2matsim.osm.OsmTransitScheduleConverter.createStopFacilityFromOsmNode(OsmTransitScheduleConverter.java:191)
        at org.matsim.pt2matsim.osm.OsmTransitScheduleConverter.convert(OsmTransitScheduleConverter.java:109)
        at org.matsim.pt2matsim.run.Osm2TransitSchedule.run(Osm2TransitSchedule.java:63)
        at org.matsim.pt2matsim.run.Osm2TransitSchedule.main(Osm2TransitSchedule.java:46)

**Comment by polettif** [comment]
The Osm2TransitSchedule approach is rather experimental and depends a lot on the input data. Could you provide the area you used?
