### ISSUE TITLE
FastAStarLandmarksFactory ClassNotFoundException

### ISSUE THREAD

**Issue by davibicudo** [matsim-org/pt2matsim#41]
Hi Flavio,

I am struggling to run the PublicTransitMapper. You commented out the import 
import org.matsim.core.router.FastAStarLandmarksFactory;
in class
mapping.networkRouter.ScheduleRouter
When adding it back I noticed there was a build problem so probably this is not new for you.
Do you have any solution in sight or a workaround?

Here is full error:
Exception in thread "main" java.lang.NoClassDefFoundError: org/matsim/core/router/util/FastAStarLandmarksFactory
	at org.matsim.pt2matsim.mapping.networkRouter.ScheduleRoutersStandard.load(ScheduleRoutersStandard.java:80)
	at org.matsim.pt2matsim.mapping.networkRouter.ScheduleRoutersStandard.<init>(ScheduleRoutersStandard.java:54)
	at org.matsim.pt2matsim.mapping.PTMapper.run(PTMapper.java:113)
	at org.matsim.pt2matsim.mapping.PTMapper.mapScheduleToNetwork(PTMapper.java:74)
	at org.matsim.pt2matsim.run.PublicTransitMapper.run(PublicTransitMapper.java:85)
	at org.matsim.pt2matsim.run.PublicTransitMapper.main(PublicTransitMapper.java:63)
	at ch.ethz.matsim.basel.schedule.MapScheduleWithNetwork.mapScheduleToNetwork(MapScheduleWithNetwork.java:71)
	at ch.ethz.matsim.basel.schedule.MapScheduleWithNetwork.main(MapScheduleWithNetwork.java:37)
Caused by: java.lang.ClassNotFoundException: org.matsim.core.router.util.FastAStarLandmarksFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more

**Comment by polettif** [comment]
It's commented out on purpose because this FastAStarLandmarksFactory import is only available in matsim 0.10. So as a fix, just don't import it ;)

There are several LeastCostPathCalculator changes from 0.9 (which pt2matsim currently points to) and 0.10-SNAPSHOT, one of which is moving the FastAStarLandmarksFactory from core.router.util to core.router. I just prepared the code a bit for the changes when I stumbled upon them.

**Comment by davibicudo** [comment]
Hey Flavio,
After a while this issue happened again and after investigating a bit, it turned out to be because my project was using matsim 0.10 and for some reason Eclipse was routing the PTMapper through it instead of using pt2matsim's dependency version 0.9. Tricky!
