### ISSUE TITLE
Conversion to EPSG does not work with shaded jar

### ISSUE THREAD

**Issue by sebhoerl** [matsim-org/pt2matsim#64]
Command:
```
java -cp pt2matsim-18.8-SNAPSHOT-shaded.jar org.matsim.pt2matsim.run.Hafas2TransitSchedule /path/to/hafas EPSG:2056 /path/to/schedule.xml.gz /path/to/vehicles.xml.gz
```
Error:
```
Exception in thread "main" java.lang.IllegalArgumentException: org.opengis.referencing.datum.DatumFactory is not an ImageIO SPI class
	at java.desktop/javax.imageio.spi.ServiceRegistry.checkClassAllowed(ServiceRegistry.java:722)
	at java.desktop/javax.imageio.spi.ServiceRegistry.<init>(ServiceRegistry.java:117)
	at org.geotools.factory.FactoryRegistry.<init>(FactoryRegistry.java:155)
	at org.geotools.factory.FactoryRegistry.<init>(FactoryRegistry.java:146)
	at org.geotools.factory.FactoryCreator.<init>(FactoryCreator.java:82)
	at org.geotools.referencing.ReferencingFactoryFinder.getServiceRegistry(ReferencingFactoryFinder.java:115)
	at org.geotools.referencing.ReferencingFactoryFinder.getFactory(ReferencingFactoryFinder.java:197)
	at org.geotools.referencing.ReferencingFactoryFinder.getCRSFactory(ReferencingFactoryFinder.java:288)
	at org.geotools.referencing.CRS.parseWKT(CRS.java:535)
	at org.matsim.core.utils.geometry.geotools.MGC.getCRS(MGC.java:172)
	at org.matsim.core.utils.geometry.transformations.GeotoolsTransformation.<init>(GeotoolsTransformation.java:57)
	at org.matsim.core.utils.geometry.transformations.TransformationFactory.getCoordinateTransformation(TransformationFactory.java:80)
	at org.matsim.pt2matsim.run.Hafas2TransitSchedule.run(Hafas2TransitSchedule.java:72)
	at org.matsim.pt2matsim.run.Hafas2TransitSchedule.main(Hafas2TransitSchedule.java:58)

```
I encountered this problem before. Somehow geotools gets confused when packaging it as a shaded jar (some parts override others in the jar). I will check if I can find the fix for that again.

**Comment by sebhoerl** [comment]
Actually, it is a Java 9+ problem with geotools... there are a lot of projects having trouble with that. Possibly could be fixed by changing geotools to an updated version, but I'm not sure if there is backward compatibility?
