### ISSUE TITLE
pedestrian network very incomplete

### ISSUE THREAD

**Issue by benjaminBrownlee** [matsim-org/pt2matsim#95]
I have been trying to get this application to build me a multimodial network for pedestrians and cars for a county. In my first attempts, I took the default config and added the pedestrian subnetwork ways described in the config below. (Note that while there may exist other way definitions for pedestrians, the ones I described should make up the bulk of pedestrian links in the network). However, I got all of maybe 1000 pedestrian links, which only seemed to be concentrated in a single neighborhood. Trying to debug this issue, I tried removing the vehicular subnetwork, but then the program fails with a null pointer exception on the converter. How am I approaching this configuration file wrong? Why might it fail when I remove the vehicular subnetwork definition?

Config File:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config SYSTEM "http://www.matsim.org/files/dtd/config_v2.dtd">
<config>
	<module name="OsmConverter" >
		<param name="keepPaths" value="false" />
		<param name="keepTagsAsAttributes" value="true" />
		<param name="keepWaysWithPublicTransit" value="true" />
		<param name="maxLinkLength" value="500.0" />
		<param name="osmFile" value="maricopa.osm" />
		<param name="outputCoordinateSystem" value="EPSG:2223" />
		<param name="outputNetworkFile" value="network.xml" />
		<param name="scaleMaxSpeed" value="false" />

		<parameterset type="routableSubnetwork" >
			<param name="allowedTransportModes" value="walk" />
			<param name="subnetworkMode" value="walk" />
		</parameterset>

		<parameterset type="wayDefaultParams" >
			<param name="allowedTransportModes" value="walk" />
			<param name="freespeed" value="0.8333333333333333" />
			<param name="freespeedFactor" value="1.0" />
			<param name="laneCapacity" value="2000.0" />
			<param name="lanes" value="1.0" />
			<param name="oneway" value="false" />
			<param name="osmKey" value="highway" />
			<param name="osmValue" value="pedestrian" />
		</parameterset>
		<parameterset type="wayDefaultParams" >
			<param name="allowedTransportModes" value="walk" />
			<param name="freespeed" value="0.8333333333333333" />
			<param name="freespeedFactor" value="1.0" />
			<param name="laneCapacity" value="2000.0" />
			<param name="lanes" value="1.0" />
			<param name="oneway" value="false" />
			<param name="osmKey" value="highway" />
			<param name="osmValue" value="footway" />
		</parameterset>
		<parameterset type="wayDefaultParams" >
			<param name="allowedTransportModes" value="walk" />
			<param name="freespeed" value="0.8333333333333333" />
			<param name="freespeedFactor" value="1.0" />
			<param name="laneCapacity" value="2000.0" />
			<param name="lanes" value="1.0" />
			<param name="oneway" value="false" />
			<param name="osmKey" value="sidewalk" />
			<param name="osmValue" value="both" />
		</parameterset>
		<parameterset type="wayDefaultParams" >
			<param name="allowedTransportModes" value="walk" />
			<param name="freespeed" value="0.8333333333333333" />
			<param name="freespeedFactor" value="1.0" />
			<param name="laneCapacity" value="2000.0" />
			<param name="lanes" value="1.0" />
			<param name="oneway" value="false" />
			<param name="osmKey" value="sidewalk" />
			<param name="osmValue" value="right" />
		</parameterset>
		<parameterset type="wayDefaultParams" >
			<param name="allowedTransportModes" value="walk" />
			<param name="freespeed" value="0.8333333333333333" />
			<param name="freespeedFactor" value="1.0" />
			<param name="laneCapacity" value="2000.0" />
			<param name="lanes" value="1.0" />
			<param name="oneway" value="false" />
			<param name="osmKey" value="sidewalk" />
			<param name="osmValue" value="left" />
		</parameterset>

                <parameterset type="routableSubnetwork" >
			<param name="allowedTransportModes" value="car" />
			<param name="subnetworkMode" value="car" />
		</parameterset>

		<parameterset type="wayDefaultParams" >
			<param name="allowedTransportModes" value="car" />
			<param name="freespeed" value="33.333333333333336" />
			<param name="freespeedFactor" value="1.0" />
			<param name="laneCapacity" value="2000.0" />
			<param name="lanes" value="2.0" />
			<param name="oneway" value="true" />
			<param name="osmKey" value="highway" />
			<param name="osmValue" value="motorway" />
		</parameterset>
		<parameterset type="wayDefaultParams" >
			<param name="allowedTransportModes" value="car" />
			<param name="freespeed" value="22.22222222222222" />
			<param name="freespeedFactor" value="1.0" />
			<param name="laneCapacity" value="1500.0" />
			<param name="lanes" value="1.0" />
			<param name="oneway" value="true" />
			<param name="osmKey" value="highway" />
			<param name="osmValue" value="motorway_link" />
		</parameterset>
		<parameterset type="wayDefaultParams" >
			<param name="allowedTransportModes" value="car" />
			<param name="freespeed" value="22.22222222222222" />
			<param name="freespeedFactor" value="1.0" />
			<param name="laneCapacity" value="2000.0" />
			<param name="lanes" value="2.0" />
			<param name="oneway" value="false" />
			<param name="osmKey" value="highway" />
			<param name="osmValue" value="trunk" />
		</parameterset>
		<parameterset type="wayDefaultParams" >
			<param name="allowedTransportModes" value="car" />
			<param name="freespeed" value="13.88888888888889" />
			<param name="freespeedFactor" value="1.0" />
			<param name="laneCapacity" value="1500.0" />
			<param name="lanes" value="1.0" />
			<param name="oneway" value="false" />
			<param name="osmKey" value="highway" />
			<param name="osmValue" value="trunk_link" />
		</parameterset>
		<parameterset type="wayDefaultParams" >
			<param name="allowedTransportModes" value="car" />
			<param name="freespeed" value="22.22222222222222" />
			<param name="freespeedFactor" value="1.0" />
			<param name="laneCapacity" value="1500.0" />
			<param name="lanes" value="1.0" />
			<param name="oneway" value="false" />
			<param name="osmKey" value="highway" />
			<param name="osmValue" value="primary" />
		</parameterset>
		<parameterset type="wayDefaultParams" >
			<param name="allowedTransportModes" value="car" />
			<param name="freespeed" value="16.666666666666668" />
			<param name="freespeedFactor" value="1.0" />
			<param name="laneCapacity" value="1500.0" />
			<param name="lanes" value="1.0" />
			<param name="oneway" value="false" />
			<param name="osmKey" value="highway" />
			<param name="osmValue" value="primary_link" />
		</parameterset>
		<parameterset type="wayDefaultParams" >
			<param name="allowedTransportModes" value="car" />
			<param name="freespeed" value="8.333333333333334" />
			<param name="freespeedFactor" value="1.0" />
			<param name="laneCapacity" value="1000.0" />
			<param name="lanes" value="1.0" />
			<param name="oneway" value="false" />
			<param name="osmKey" value="highway" />
			<param name="osmValue" value="secondary" />
		</parameterset>
		<parameterset type="wayDefaultParams" >
			<param name="allowedTransportModes" value="car" />
			<param name="freespeed" value="8.333333333333334" />
			<param name="freespeedFactor" value="1.0" />
			<param name="laneCapacity" value="1000.0" />
			<param name="lanes" value="1.0" />
			<param name="oneway" value="false" />
			<param name="osmKey" value="highway" />
			<param name="osmValue" value="secondary_link" />
		</parameterset>
		<parameterset type="wayDefaultParams" >
			<param name="allowedTransportModes" value="car" />
			<param name="freespeed" value="6.944444444444445" />
			<param name="freespeedFactor" value="1.0" />
			<param name="laneCapacity" value="600.0" />
			<param name="lanes" value="1.0" />
			<param name="oneway" value="false" />
			<param name="osmKey" value="highway" />
			<param name="osmValue" value="tertiary" />
		</parameterset>
		<parameterset type="wayDefaultParams" >
			<param name="allowedTransportModes" value="car" />
			<param name="freespeed" value="6.944444444444445" />
			<param name="freespeedFactor" value="1.0" />
			<param name="laneCapacity" value="600.0" />
			<param name="lanes" value="1.0" />
			<param name="oneway" value="false" />
			<param name="osmKey" value="highway" />
			<param name="osmValue" value="tertiary_link" />
		</parameterset>
		<parameterset type="wayDefaultParams" >
			<param name="allowedTransportModes" value="car" />
			<param name="freespeed" value="6.944444444444445" />
			<param name="freespeedFactor" value="1.0" />
			<param name="laneCapacity" value="600.0" />
			<param name="lanes" value="1.0" />
			<param name="oneway" value="false" />
			<param name="osmKey" value="highway" />
			<param name="osmValue" value="unclassified" />
		</parameterset>
		<parameterset type="wayDefaultParams" >
			<param name="allowedTransportModes" value="car" />
			<param name="freespeed" value="4.166666666666667" />
			<param name="freespeedFactor" value="1.0" />
			<param name="laneCapacity" value="600.0" />
			<param name="lanes" value="1.0" />
			<param name="oneway" value="false" />
			<param name="osmKey" value="highway" />
			<param name="osmValue" value="residential" />
		</parameterset>
		<parameterset type="wayDefaultParams" >
			<param name="allowedTransportModes" value="car" />
			<param name="freespeed" value="2.7777777777777777" />
			<param name="freespeedFactor" value="1.0" />
			<param name="laneCapacity" value="300.0" />
			<param name="lanes" value="1.0" />
			<param name="oneway" value="false" />
			<param name="osmKey" value="highway" />
			<param name="osmValue" value="living_street" />
		</parameterset>
		<parameterset type="wayDefaultParams" >
			<param name="allowedTransportModes" value="rail" />
			<param name="freespeed" value="44.44444444444444" />
			<param name="freespeedFactor" value="1.0" />
			<param name="laneCapacity" value="9999.0" />
			<param name="lanes" value="1.0" />
			<param name="oneway" value="false" />
			<param name="osmKey" value="railway" />
			<param name="osmValue" value="rail" />
		</parameterset>
		<parameterset type="wayDefaultParams" >
			<param name="allowedTransportModes" value="rail" />
			<param name="freespeed" value="11.11111111111111" />
			<param name="freespeedFactor" value="1.0" />
			<param name="laneCapacity" value="9999.0" />
			<param name="lanes" value="1.0" />
			<param name="oneway" value="true" />
			<param name="osmKey" value="railway" />
			<param name="osmValue" value="tram" />
		</parameterset>
		<parameterset type="wayDefaultParams" >
			<param name="allowedTransportModes" value="rail" />
			<param name="freespeed" value="22.22222222222222" />
			<param name="freespeedFactor" value="1.0" />
			<param name="laneCapacity" value="9999.0" />
			<param name="lanes" value="1.0" />
			<param name="oneway" value="false" />
			<param name="osmKey" value="railway" />
			<param name="osmValue" value="light_rail" />
		</parameterset>
         </module>
</config>
```

Exception (when run without vehicle subnetwork or default ways):

```
2019-10-22 23:34:40,706  INFO OsmMultimodalNetworkConverter:127 Converting OSM to MATSim network...
2019-10-22 23:34:45,710  INFO OsmMultimodalNetworkConverter:147 remove unusable ways...
Exception in thread "main" java.lang.NullPointerException
        at org.matsim.pt2matsim.osm.OsmMultimodalNetworkConverter.getWayDefaultParams(OsmMultimodalNetworkConverter.java:546)
        at org.matsim.pt2matsim.osm.OsmMultimodalNetworkConverter.convertToNetwork(OsmMultimodalNetworkConverter.java:149)
        at org.matsim.pt2matsim.osm.OsmMultimodalNetworkConverter.convert(OsmMultimodalNetworkConverter.java:106)
        at org.matsim.pt2matsim.run.Osm2MultimodalNetwork.run(Osm2MultimodalNetwork.java:92)
        at org.matsim.pt2matsim.run.Osm2MultimodalNetwork.run(Osm2MultimodalNetwork.java:64)
        at org.matsim.pt2matsim.run.Osm2MultimodalNetwork.main(Osm2MultimodalNetwork.java:47)
```

**Comment by benjaminBrownlee** [comment]
I also wanted to note that I tried adding some of the more uncommon way definitions for pedestrians, such as living_street, and I actually found the number of walking links in my output network decreasing. There is definitely something going wrong here.

**Comment by polettif** [comment]
> I tried removing the vehicular subnetwork, but then the program fails with a null pointer exception on the converter.

Does your config after removing the subnetworks look like this?

```<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config SYSTEM "http://www.matsim.org/files/dtd/config_v2.dtd">
<config>
	<module name="OsmConverter" >
		<param name="keepPaths" value="false" />
		<param name="keepTagsAsAttributes" value="true" />
		<param name="keepWaysWithPublicTransit" value="true" />
		<param name="maxLinkLength" value="500.0" />
		<param name="osmFile" value="maricopa.osm" />
		<param name="outputCoordinateSystem" value="EPSG:2223" />
		<param name="outputNetworkFile" value="network.xml" />
		<param name="scaleMaxSpeed" value="false" />

		<parameterset type="routableSubnetwork" >
			<param name="allowedTransportModes" value="walk" />
			<param name="subnetworkMode" value="walk" />
		</parameterset>

		<parameterset type="wayDefaultParams" >
			<param name="allowedTransportModes" value="walk" />
			<param name="freespeed" value="0.8333333333333333" />
			<param name="freespeedFactor" value="1.0" />
			<param name="laneCapacity" value="2000.0" />
			<param name="lanes" value="1.0" />
			<param name="oneway" value="false" />
			<param name="osmKey" value="highway" />
			<param name="osmValue" value="pedestrian" />
		</parameterset>
		<parameterset type="wayDefaultParams" >
			<param name="allowedTransportModes" value="walk" />
			<param name="freespeed" value="0.8333333333333333" />
			<param name="freespeedFactor" value="1.0" />
			<param name="laneCapacity" value="2000.0" />
			<param name="lanes" value="1.0" />
			<param name="oneway" value="false" />
			<param name="osmKey" value="highway" />
			<param name="osmValue" value="footway" />
		</parameterset>
		<parameterset type="wayDefaultParams" >
			<param name="allowedTransportModes" value="walk" />
			<param name="freespeed" value="0.8333333333333333" />
			<param name="freespeedFactor" value="1.0" />
			<param name="laneCapacity" value="2000.0" />
			<param name="lanes" value="1.0" />
			<param name="oneway" value="false" />
			<param name="osmKey" value="sidewalk" />
			<param name="osmValue" value="both" />
		</parameterset>
		<parameterset type="wayDefaultParams" >
			<param name="allowedTransportModes" value="walk" />
			<param name="freespeed" value="0.8333333333333333" />
			<param name="freespeedFactor" value="1.0" />
			<param name="laneCapacity" value="2000.0" />
			<param name="lanes" value="1.0" />
			<param name="oneway" value="false" />
			<param name="osmKey" value="sidewalk" />
			<param name="osmValue" value="right" />
		</parameterset>
		<parameterset type="wayDefaultParams" >
			<param name="allowedTransportModes" value="walk" />
			<param name="freespeed" value="0.8333333333333333" />
			<param name="freespeedFactor" value="1.0" />
			<param name="laneCapacity" value="2000.0" />
			<param name="lanes" value="1.0" />
			<param name="oneway" value="false" />
			<param name="osmKey" value="sidewalk" />
			<param name="osmValue" value="left" />
		</parameterset>

         </module>
</config>
```

In that case the NULL pointer exception happens because [there are no railwayDefaults defined](https://github.com/matsim-org/pt2matsim/blob/fb4e748220f48c20f72ec103c1261d57f6cd6ca4/src/main/java/org/matsim/pt2matsim/osm/OsmMultimodalNetworkConverter.java#L546). This is definitely a bug. In the meantime, try keeping one `wayDefaultParam` for rail in there, you can use an `osmValue` that doesn't exists so your network shouldn't contain any railway links.

**Comment by benjaminBrownlee** [comment]
Ok, by not removing the rail ways when commenting out the vehicular network, I was able to get the pedestrian and rail only network to build. However, the network for walking is still incredibly small.

I noticed that the pedestrian network that did output is always one continuous network, and also not always in the same place as earlier. Could this be an issue with the network cleaner? 

Network File:

```
cat network.xml | grep "modes=\"walk\"" | wc -l
5358
```

Network Visualization:
red is rail
blue is pedestrian

![maripoca](https://user-images.githubusercontent.com/29786277/67417006-bdc40200-f57c-11e9-8818-a121b126cca7.png)

**Comment by benjaminBrownlee** [comment]
That makes sense. I think most my pedestrian traffic in my simulation is very local (i.e. a walk from a parking garage to a workplace), so maybe a fractured network may work, but I'm not an expert regarding how MATSim works. Regardless, I would like to at least visualize the full, uncleaned pedestrian network. Which parameterset controls the network cleaner? And for that matter, where can I find the documentation for all the config options?

**Comment by benjaminBrownlee** [comment]
Ok, I am now able to extract all the pedestrian paths, but I realize the reason for the fractured network is that your code does not support extracting sidewalks into a subnetwork. I guess my best next move is to assume that sidewalks exist on a certain tiers of highway or fork your repository.

**Comment by polettif** [comment]
Yes, the converter currently only looks at `highway=*` or `railway=*` tags and nothing else. [Sidewalks](https://wiki.openstreetmap.org/wiki/Sidewalks) are generally tagged as `highway=*` and `sidewalk=*`. 

However, all OSM tags are stored as attributes in the converted network file, for example: 
```xml
<link id="99997" from="A" to="B length="100" freespeed="4.166" capacity="600.0" permlanes="1.0" oneway="1" modes="bus,car" >
	<attributes>
		<attribute name="osm:way:highway" class="java.lang.String" >residential</attribute>
		<attribute name="osm:way:sidewalk" class="java.lang.String" >both</attribute>
		<attribute name="osm:way:id" class="java.lang.Long" >1234</attribute>
		<attribute name="osm:way:name" class="java.lang.String" >Example St</attribute>
	</attributes>
</link>
```
So you could read the converted network, look for all links with a sidewalk tag and add them to the network as walk links. Naturally, this requires that sidewalks are actually tagged in your area.

> Which parameterset controls the network cleaner? And for that matter, where can I find the documentation for all the config options?

For posterity: the `routableSubnetwork` parametersets control the network cleaner. The documentation is in the code and written shown in the default config file (created by `CreateDefaultOsmConfig`)
